import { z } from "zod";
import type { ProviderConfig } from "@humansignal/app-common/blocks/StorageProviderForm/types/provider";
import { IconCloudProviderS3 } from "@humansignal/icons";
import { i18n } from "../../../../../../../libs/datamanager/src/utils/i18n";

export const s3Provider: ProviderConfig = {
  name: "s3",
  title: i18n.t('storage.amazonS3'),
  description: i18n.t('storage.amazonS3Description'),
  icon: IconCloudProviderS3,
  fields: [
    {
      name: "bucket",
      type: "text",
      label: i18n.t('storage.bucketName'),
      required: true,
      placeholder: i18n.t('storage.bucketNamePlaceholder'),
      schema: z.string().min(1, i18n.t('storage.bucketNameRequired')),
    },
    {
      name: "region_name",
      type: "text",
      label: i18n.t('storage.regionName'),
      placeholder: i18n.t('storage.regionNamePlaceholder'),
      schema: z.string().optional().default(""),
    },
    {
      name: "s3_endpoint",
      type: "text",
      label: i18n.t('storage.s3Endpoint'),
      placeholder: i18n.t('storage.s3EndpointPlaceholder'),
      schema: z.string().optional().default(""),
    },
    {
      name: "prefix",
      type: "text",
      label: i18n.t('storage.bucketPrefix'),
      placeholder: i18n.t('storage.bucketPrefixPlaceholder'),
      schema: z.string().optional().default(""),
      target: "export",
    },
    {
      name: "aws_access_key_id",
      type: "password",
      label: i18n.t('storage.accessKeyId'),
      required: true,
      placeholder: i18n.t('storage.accessKeyIdPlaceholder'),
      autoComplete: "off",
      accessKey: true,
      schema: z.string().min(1, i18n.t('storage.accessKeyIdRequired')),
    },
    {
      name: "aws_secret_access_key",
      type: "password",
      label: i18n.t('storage.secretAccessKey'),
      required: true,
      placeholder: i18n.t('storage.secretAccessKeyPlaceholder'),
      autoComplete: "new-password",
      accessKey: true,
      schema: z.string().min(1, i18n.t('storage.secretAccessKeyRequired')),
    },
    {
      name: "aws_session_token",
      type: "password",
      label: i18n.t('storage.sessionToken'),
      placeholder: i18n.t('storage.sessionTokenPlaceholder'),
      autoComplete: "new-password",
      schema: z.string().optional().default(""),
    },
    {
      name: "presign",
      type: "toggle",
      label: i18n.t('storage.usePresignedUrls'),
      description: i18n.t('storage.usePresignedUrlsDescription'),
      schema: z.boolean().default(true),
      target: "import",
      resetConnection: false,
    },
    {
      name: "presign_ttl",
      type: "counter",
      label: i18n.t('storage.expirePresignedUrls'),
      min: 1,
      max: 10080,
      step: 1,
      schema: z.number().min(1).max(10080).default(15),
      target: "import",
      resetConnection: false,
      dependsOn: {
        field: "presign",
        value: true,
      },
    },
  ],
  layout: [
    { fields: ["bucket"] },
    { fields: ["region_name"] },
    { fields: ["s3_endpoint"] },
    { fields: ["prefix"] },
    { fields: ["aws_access_key_id"] },
    { fields: ["aws_secret_access_key"] },
    { fields: ["aws_session_token"] },
    { fields: ["presign", "presign_ttl"] },
  ],
};
